### PR TITLE
Fix issue 57 - errors on VCL reload because of duplicated counters

### LINKED ISSUE #57: Regression after #56 when running varnishreload ("... was collected before with the same name and label values")
* **Varnish** 6.3.1
* **prometheus_varnish_exporter** 1.5.1

------------------
After my patch in #56 was introduced, there are now problem with duplicate metric names. For some reason I missed this... Apologies.

Since varnishreload does not remove the old VCL automatically, there will be VBE stats for both VCLs. This causes double metrics to be registered, triggering errors in prometheus client lib:

```
collected metric "varnish_backend_happy" { label:<name:"backend" value:"backendname" > label:<name:"server" value:"unknown" > gauge:<value:1.3510798882111488e+16 > } was collected before with the same name and label values
collected metric "varnish_backend_happy" { label:<name:"backend" value:"backendname" > label:<name:"server" value:"unknown" > gauge:<value:6.597069766656e+12 > } was collected before with the same name and label values
```

from:
```
VBE.boot.backendname.happy Happy health probes
VBE.reload_20191114_072450_277.backendname.happy Happy health probes
```

Note that these are seen when actually calling the scrape endpoint!

Not sure how to work around this, varnishstat does not seem to identify the currently active VCL, or am I missing something?

### PR DESCRIPTION
**Pull request by LorenzoPeri**
Fixes #57 

**Issue**
The exporter fails when VCL is reloaded.
This happens because Varnish backend counters (VBE) are repeated for each reload with its timestamp:
Example: `VBE.boot.default.happy` and `VBE.reload_20210114_155148_19902.default.happy`
... thus generating duplicated metrics.

The `-p vcl_cooldown=1`  workaround is not good enough, because old counters are still present in varnishstat for some time (granularity is 30s, see https://varnish-cache.org/docs/6.5/reference/varnishd.html#vcl-cooldown).

The result is that on each reload the exporter keeps failing for some time (1m in my tests with `-p vcl_cooldown=1`, 10m without it).

**Solution**
I propose to consider only the counters with the most recent timestamp.
I quickly calculate the most recent timestamp by checking the ".happy" counters, then I filter out the outdated counters.
Should work for any Varnish version.

Tests included:
- unit test for the 2 new methods
- I duplicated VBE metrics in the `6.5.1.json` file with 2 different timestamps to simulate 2 consecutive VCL reloads. Existing tests would fail without the fix.

### CODE REVIEW

File: varnish.go [hunk 1]
```diff
@@ -15,6 +15,11 @@ import (
 	"github.com/prometheus/client_golang/prometheus"
 )
 
+const (
+	vbeReload       = "VBE.reload_"
+	vbeReloadLength = len(vbeReload)
```
Comment (jonnenauha) [inline varnish.go:20]: You can do this inline in `findMostRecentVbeReloadPrefix`, no need to make this globals constant.

File: varnish.go [hunk 2]
```diff
@@ -212,6 +223,31 @@ func executeVarnishstat(varnishstatExe string, params ...string) (*bytes.Buffer,
...
+		// Checking only the required ".happy" stat
+		if strings.HasPrefix(vName, vbeReload) && strings.HasSuffix(vName, ".happy") {
+			dotAfterPrefixIndex := vbeReloadLength + strings.Index(vName[vbeReloadLength:], ".")
+			vbeReloadPrefix := vName[:dotAfterPrefixIndex]
+			if strings.Compare(vbeReloadPrefix, mostRecentVbeReloadPrefix) > 0 {
+				mostRecentVbeReloadPrefix = vbeReloadPrefix
+			}
+		}
+	}
+	return mostRecentVbeReloadPrefix
```
Comment (jonnenauha) [inline varnish.go:241]: If there is only one set on `reload_` entries, this function will return the only ones timestamp and that will then be (unintentionally?) ignored in `ScrapeVarnishFrom`. Did you intend this, I assume letting the one go through is ok, if its ok to let one of many through as well.
```suggestion
	mostRecentVbeReloadPrefix  := ""
	numReloadedPrefix := 0	
	for vName, _ := range countersJSON {
		// Checking only the required ".happy" stat
		if strings.HasPrefix(vName, vbeReload) && strings.HasSuffix(vName, ".happy") {
			numReloadedPrefix++
			dotAfterPrefixIndex := vbeReloadLength + strings.Index(vName[vbeReloadLength:], ".")
			vbeReloadPrefix := vName[:dotAfterPrefixIndex]
			if strings.Compare(vbeReloadPrefix, mostRecentVbeReloadPrefix) > 0 {
				mostRecentVbeReloadPrefix = vbeReloadPrefix
			}
		}
	}
	if numReloadedPrefix <= 1  {
		return ""
	}
	return mostRecentVbeReloadPrefix
```

**Review by jonnenauha — COMMENTED** [review]
Question: Did I understand right that the bug is that over time the stats contain these `reload_` prefixed entries. They do go away after that cooldown. but while they exist it breaks the whole metrics scrape and export? 

But if the names are unique by the timestamp there, why is prometheus giving and error? Does our code somehow strip the timestamp out or the metric identifier? And then we end up with multiple metrics with the same name/labels which prometheus then rejects?

Good code in general. Left some suggestions and I think one bug.

**Comment by LorenzoPeri** [comment]
> Question: Did I understand right that the bug is that over time the stats contain these `reload_` prefixed entries. They do go away after that cooldown. but while they exist it breaks the whole metrics scrape and export?

Correct.

Varnish starts with just the `VBE.boot` counters.
On each Varnish reload, a new set of `VBE.reload_[timestamp]` counters is added.
The old counters will disappear after the cooldown.

For example, if you reload Varnish many times in a row, you could end up with many concurrent sets of `VBE.reload_` counters, but after the cooldown only the most recent will be present (note that also the original `VBE.boot` set will be gone, it behaves like the others).

The only way to expose all the counters at the same time would probably be to add the timestamp as additional label on the Prometheus metrics. This way the conflict would be avoided, **but** a new time series would be created in Prometheus on each Varnish reload. IMHO it would not be good memory-wise for Prometheus and also it would be harder to extract useful metrics (like, how to ignore the outdated ones in queries?).

I think it's better to just expose the current active values.

> But if the names are unique by the timestamp there, why is prometheus giving and error? Does our code somehow strip the timestamp out or the metric identifier? And then we end up with multiple metrics with the same name/labels which prometheus then rejects?

Also correct. The timestamp is not part of the exported metrics (name or tags), so there are naming conflicts.

> Good code in general. Left some suggestions and I think one bug (though I assume its possible to have only one unique reload_ entries you might know better).

Thanks!

File: varnish.go (hunk 2 above)
Comment (LorenzoPeri) [reply varnish.go:241]: > If there is only one set on reload_ entries, this function will return the only ones timestamp

Correct

> and that will then be (unintentionally?) ignored in ScrapeVarnishFrom.

I don't think this is true. `ScrapeVarnishFrom` will use `isOutdatedVbe` to determine that the VBE counters are not, in fact, outdated, so they won't be skipped (this should be covered by the `current VCL version` test case of `Test_IsOutdatedVbe`).

Let me know if I missed something!

File: varnish.go (hunk 1 above)
Comment (LorenzoPeri) [reply varnish.go]: Ok, it was maybe and excessive attempt of optimization on my side. :D
Done: feb61723705840fcea26a8e76be989e666ec8198

**Comment by zipkid** [comment]
Is it possible to create a release containing this fix?

**Comment by jonnenauha** [comment]
@zipkid latest release has this https://github.com/jonnenauha/prometheus_varnish_exporter/releases/tag/1.6.1
